### ISSUE TITLE
"Dynamic" recipes

### ISSUE THREAD

**Issue by nicogelders** [datarootsio/databooks#28]
Make recipes take variables so that they could be reused more easily.

Example:

The recipe:
```python
max_cells = RecipeInfo(
    src="len(nb.cells) < amount_max",
    description="Assert that there are less than 'amount_max' cells in the notebook.",
)
```

The command:
```bash
databooks assert path/to/nbs --recipe max_cells --amount_max 10
```

```bash
databooks assert path/to/nbs --recipe max_cells --help
```
Would return the arguments of that recipe

**Comment by nicogelders** [comment]
The --help thing might be tricky maybe do something like this

```bash
databooks inspect-recipe max_cells
```

**Comment by murilo-cunha** [comment]
After some thought, I see 3 ways of accomplishing this:

1. We could [allow extra arguments](https://typer.tiangolo.com/tutorial/commands/context/#configuring-the-context) and if they are passed we replace the string with the right values
2. We could dynamically create [subcommands](https://typer.tiangolo.com/tutorial/subcommands/nested-subcommands/) - one for each recipe with it's own help and call each subcommand after `assert` has run
3. Create another command entirely for recipes

Some points to consider:

- What if the user passes multiple recipes?
- What if the arguments have similar names?
- How can we enforce that the arguments go to the correct recipe?

As of now, I do **not** see a feature like this because

- It may make the app less intuitive for users and add some unnecessary complexity
- We only have one recipe that it'd make sense to pass arguments (`max-cells`)
- If a user really wants another value, he/she can easily do this by passing the expression instead of the recipe + argument (`databooks assert "len(nb.cells) < 10"`)

That being said, I'm open to revisit this once we have more recipes/there's community interest in a feature like this. If there's a simple way to go around this I'm also open to review any PRs regarding this.

Thanks for your suggestion! 🚀
